#!/usr/bin/env python3

from spot_driver.spot_gripper_see_obstacle import SpotGripperObstacleDetector
import rospy

if __name__ == "__main__":
    rospy.init_node('spot_gripper_see_obstacle')
    SG = SpotGripperObstacleDetector()
    rospy.spin()
